ALTER TABLE admin_user ALTER COLUMN created_at SET DATA TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';
ALTER TABLE admin_user ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE admin_user ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE admin_user ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE admin_user ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE admin_user ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE admin_user ALTER COLUMN last_login_at SET DATA TYPE TIMESTAMP WITH TIME ZONE USING last_login_at AT TIME ZONE 'UTC';

ALTER TABLE admin_user ALTER COLUMN locked_until SET DATA TYPE TIMESTAMP WITH TIME ZONE USING locked_until AT TIME ZONE 'UTC';
